### ISSUE TITLE
Issue reg training BERT model on PolicyQA

### ISSUE THREAD

**Issue by txmaniac** [wasiahmad/PolicyQA#1]
Hello,

I'm trying to train a BERT model for QA task on PolicyQA dataset. I have written my own training script etc. I'm not able to get the evaluation and test results which you guys have got in the paper. But when I use your run_squad.py script, the results match.

I need some help in understanding what I could be doing wrong.

Model used : Bert-base-uncased
Training params : All which are mentioned in your paper

Help from your end would be appreciated :)

**Comment by wasiahmad** [comment]
Do you want me to find the problem in your implementation from the piece of information provided above? I am sorry but I do not know magic. The code that reproduces the results are released and you can carefully explore it to find the issue in your implementation.
